version: '3'
services:
   nginx:
    image: nginx:latest
    container_name: open0page
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/usr/share/nginx/html